services:
  palbot:
    image: ghcr.io/mtgvim/palworld-server-bot:latest
    restart: unless-stopped
    environment:
      DISCORD_BOT_TOKEN: "여기에_봇토큰"
      RCON_HOST: 172.17.0.1
      RCON_PORT: "25575"
      RCON_PASSWORD: "여기에_rcon비번"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock