services:
  palworld-server-bot:
    image: ghcr.io/MTGVim/palworld-server-bot:latest
    container_name: palworld-bot
    restart: unless-stopped
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      RCON_HOST: palworld-server
      RCON_PORT: 25575
      RCON_PASSWORD: ${RCON_PASSWORD}
#     networks:
#       - palworld-server

# networks:
#   palworld-server:
#     external: true
